name: CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js enviroment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      # Configurando cache para o comando yarn não ficar rodando tudo do zero sempre
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Instalar as dependências Yarn
      - name: Install dependencies
        run: yarn

      # Copiar os arquivos para o servidor
      - name: Copy archives to Google Server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER_NAME}}
          port: ${{secrets.PORT}}
          key: ${{secrets.KEY}}
          source: ".,!node_modules"
          target: "app"

      # Rodar yarn dentro do servidor e restart do server with pm2
      - name: Install dependencies on Google Server and restart API using pm2
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER_NAME }}
            port: ${{ secrets.PORT }}
            key: ${{secrets.KEY}}
            script: |
              cd ~/app
              yarn
